export enum AppConstants {
	ADD_FILE,
	MODEL_LOADED,
	SELECT_DATASOURCE,
	PREVIEW_READY,
	DROP_COLUMN,
	DROP_ROW,
	DROP_MEASURE,
	REMOVE_COLUMN,
	REMOVE_ROW,
	REMOVE_MEASURE
}

export enum ApplicationTabs {
	DATASOURCES_VIEW,
	CHART_VIEW
}